# This is a preferences file for the bacon tool
# More info at https://github.com/Canop/bacon

# Uncomment and change the value (true/false) to
# specify whether bacon should start in summary mode
#
# summary = true

# Uncomment and change the value (true/false) to
# specify whether bacon should start with lines wrapped
#
wrap = true

# In "reverse" mode, the focus is at the bottom, item
# order is reversed, and the status bar is on top
#
# reverse = true

# Uncomment this to have bacon always export locations
# This is equivalent to always adding -e to bacon commands
# but can still be cancelled on specific launches with -E
#
export_locations = true

# Uncomment and change the key-bindings you want to define
# (some of those ones are the defaults)
[keybindings]
# Down = "scroll-lines(1)"
# End = "scroll-to-bottom"
# Home = "scroll-to-top"
# PageDown = "scroll-pages(1)"
# PageUp = "scroll-pages(-1)"
# Up = "scroll-lines(-1)"
# ctrl-c = "quit"
# ctrl-q = "quit"
# esc = "back"
# t = "toggle-backtrace"
Space = "scroll-pages(1)"
a = "job:check-all"
c = "job:clippy"
d = "job:doc-open"
g = "scroll-to-top"
i = "job:initial"
j = "scroll-lines(1)"
k = "scroll-lines(-1)"
n = "job:nextest"
q = "quit"
r = "job:run"
s = "toggle-summary"
shift-b = "toggle-backtrace"
shift-g = "scroll-to-bottom"
t = "job:test"
w = "toggle-wrap"

[jobs.nextest]
command = ["cargo", "nextest", "run", "--color", "always"]
need_stdout = true
watch = ["tests"]
